# Generated by Django 5.2.6 on 2026-05-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
